dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.116
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.116
- name: mqttserver
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.123
- name: priluxswiftlibrary
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.75
- name: priluxwebui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.426
